name: Publish Retype powered website to GitHub
on:
  workflow_dispatch:
  push:
    branches:
      - build

jobs:
  getProjetREADME: 
    name: Get all the projet readme
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.4.0]

    steps:
      - uses: linhbn123/rebase-pull-requests@v1.0.1
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - uses: linhbn123/rebase-pull-requests@v1.0.1
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Executing the script
        run: deno run -A --unstable --no-check ./script/updateProjetReadme.ts
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main' 