name: Publish Retype powered website to GitHub
on:
  workflow_dispatch:
  push:
    branches:
      - build

jobs:

  publish:
    name: Publish to the retype branch
    needs: getProjetREADME

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          branch: retype
          update-branch: true
